version = 0.1

[default.deploy.parameters]
stack_name = "fcg-notifications-serverless"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "NewRelicLicenseKeySecretName=\"fcg/notifications/new-relic-license-key\""
