<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\Notifications.Domain\Notifications.Domain.csproj"/>
        <ProjectReference Include="..\Notifications.Application\Notifications.Application.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.103.5"/>
        <PackageReference Include="FiapCloudGames.Contracts" Version="6.0.0"/>
        <PackageReference Include="Serilog" Version="4.2.0"/>
        <PackageReference Include="Serilog.AspNetCore" Version="8.1.1"/>
    </ItemGroup>

</Project>
